services:
  stats-server:
    build:
      context: ./stats/stats-server
    ports:
      - "9090:9090"
    environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
       - SPRING_DATASOURCE_USERNAME=user
       - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:17
    container_name: ewm-stat-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
